# Coleta de Dados
## Ativo - ITUB4

In [ ]:
# Definindo o ticker/ativo e a data de início para a coleta dos dados
TICKER = 'ITUB4.SA'
# Definindo a data de início (5 anos atrás a partir de hoje)
START_DATE = (datetime.now() - timedelta(days=5*365)).strftime('%Y-%m-%d')
#Definindo a data de término (hoje)
END_DATE = datetime.now().strftime('%Y-%m-%d')

In [ ]:
# Realizando o download dos dados históricos do ativo utilizando a biblioteca yfinance do ativo ITUB4.SA, com os ajustes automáticos para dividendos e splits, e especificando o período de 5 anos
df = yf.download(TICKER, auto_adjust=True, start=START_DATE, end=END_DATE)

[*********************100%***********************]  1 of 1 completed

In [ ]:
# Removendo o droplevel do nível "Ticker"
df.columns = df.columns.droplevel("Ticker")

In [ ]:
df.head()

Price           Close       High        Low       Open    Volume
Date
2021-05-03  17.981256  18.168159  17.775020  17.852358  46978032
2021-05-04  17.214302  18.271264  17.175634  18.110143  89509379
2021-05-05  17.704119  17.820127  17.091854  17.336761  56856659
2021-05-06  17.594553  17.800790  17.459210  17.633222  27016611
2021-05-07  17.807234  17.852348  17.555883  17.665447  30255405

In [ ]:
df.tail()

Price           Close       High        Low       Open    Volume
Date
2026-04-24  44.369999  44.520000  43.889999  44.459999  18234600
2026-04-27  43.990002  44.560001  43.980000  44.500000  13718400
2026-04-28  44.099998  44.610001  43.200001  43.680000  27131800
2026-04-29  42.869999  44.009998  42.759998  43.849998  18628100
2026-04-30  43.189999  43.560001  43.130001  43.320000  22735500

In [ ]:
df.shape

(1247, 5)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1247 entries, 2021-05-03 to 2026-04-30
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1247 non-null   float64
 1   High    1247 non-null   float64
 2   Low     1247 non-null   float64
 3   Open    1247 non-null   float64
 4   Volume  1247 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.5 KB

In [ ]:
# Cálculo da Média Móvel Exponencial (EMA) de 60 dias
df['EMA_60'] = df['Close'].ewm(span=60, adjust=False).mean()

In [ ]:
print(df[["Close", "EMA_60"]].head(65))
print(f"Valores nulos na EMA_60: {df['EMA_60'].isna().sum()}")

Price           Close     EMA_60
Date
2021-05-03  17.981256  17.981256
2021-05-04  17.214302  17.956110
2021-05-05  17.704119  17.947848
2021-05-06  17.594553  17.936265
2021-05-07  17.807234  17.932034
...               ...        ...
2021-07-28  19.896946  19.280841
2021-07-29  19.793549  19.297651
2021-07-30  19.580301  19.306918
2021-08-02  19.699917  19.319803
2021-08-03  19.893864  19.338625

[65 rows x 2 columns]
Valores nulos na EMA_60: 0

In [ ]:
# Captando informações adicionais sobre o dataset, como valores ausentes, estatísticas descritivas e linhas com volume zerado
print("=== Valores ausentes ===")
print(df.isnull().sum())

print("\n=== Estatísticas descritivas ===")
print(df.describe())

print("\n=== Linhas com volume zerado ===")
zero_vol = df[df["Volume"] == 0]
print(f"Total: {len(zero_vol)}")
print(zero_vol)

=== Valores ausentes ===
Price
Close     0
High      0
Low       0
Open      0
Volume    0
EMA_60    0
dtype: int64

=== Estatísticas descritivas ===
Price        Close         High          Low         Open        Volume  \
count  1247.000000  1247.000000  1247.000000  1247.000000  1.247000e+03
mean     23.966907    24.215549    23.715908    23.961687  3.288489e+07
std       7.995119     8.055403     7.929616     7.992016  1.622914e+07
min      13.789177    14.026130    13.762846    13.945731  6.695412e+06
25%      17.810044    18.013663    17.615355    17.819681  2.198434e+07
50%      20.959099    21.204540    20.720120    20.926794  2.946514e+07
75%      27.530972    27.757023    27.138300    27.451340  4.029414e+07
max      48.925987    49.223288    48.162912    48.608865  1.820390e+08

Price       EMA_60
count  1247.000000
mean     23.357064
std       7.249738
min      15.169766
25%      17.605275
50%      19.521267
75%      26.771031
max      43.810181

=== Linhas com volume zerado ===
Total: 0
Empty DataFrame
Columns: [Close, High, Low, Open, Volume, EMA_60]
Index: []

In [ ]:
df.head()

Price           Close       High        Low       Open    Volume     EMA_60
Date
2021-05-03  17.981256  18.168159  17.775020  17.852358  46978032  17.981256
2021-05-04  17.214302  18.271264  17.175634  18.110143  89509379  17.956110
2021-05-05  17.704119  17.820127  17.091854  17.336761  56856659  17.947848
2021-05-06  17.594553  17.800790  17.459210  17.633222  27016611  17.936265
2021-05-07  17.807234  17.852348  17.555883  17.665447  30255405  17.932034

In [ ]:
# Removendo linhas com volume zerado
df = df[df["Volume"] > 0]
print(f"Dataset após remoção de linhas com volume zerado: {df.shape}")

Dataset após remoção de linhas com volume zerado: (1247, 6)

In [ ]:
#Gerando arquivo CSV do dataset processado
df.to_csv("/Users/lucaszaninidasilva/Mackenzie/SetimoSemestre/IA/PROJETO/src/database/processed/ITUB4_processed.csv", index=True)