# Coleta de Dados
## Ativo - ITUB4

In [15]:
# Importando as bibliotecas necessárias

import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

In [16]:
# Definindo o ticker/ativo e a data de início para a coleta dos dados
TICKER = 'ITUB4.SA'
# Definindo a data de início (5 anos atrás a partir de hoje)
START_DATE = (datetime.now() - timedelta(days=5*365)).strftime('%Y-%m-%d')
#Definindo a data de término (hoje)
END_DATE = datetime.now().strftime('%Y-%m-%d')

In [17]:
# Realizando o download dos dados históricos do ativo utilizando a biblioteca yfinance do ativo ITUB4.SA, com os ajustes automáticos para dividendos e splits, e especificando o período de 5 anos
df = yf.download(TICKER, auto_adjust=True, start=START_DATE, end=END_DATE)

[*********************100%***********************]  1 of 1 completed

In [18]:
# Removendo o droplevel do nível "Ticker"
df.columns = df.columns.droplevel("Ticker")

In [19]:
df.head()

Price           Close       High        Low       Open    Volume
2021-05-28  19.119923  19.190903  18.713389  18.752107  29988923
2021-05-31  19.061853  19.313517  18.965059  19.145740  17563652
2021-06-01  19.755884  19.755884  19.239391  19.265215  48906171
2021-06-02  20.414419  20.524174  19.775258  19.788170  64182184
2021-06-04  20.840530  20.905092  20.298212  20.382142  41730769

In [20]:
df.tail()

Price           Close       High        Low       Open    Volume
2026-05-20  39.669998  39.980000  39.099998  39.220001  38261500
2026-05-21  40.119999  40.450001  39.250000  39.430000  40949800
2026-05-22  39.430000  40.040001  39.310001  40.009998  21539700
2026-05-25  40.320000  40.490002  39.860001  39.860001  11436200
2026-05-26  40.060001  40.360001  39.650002  40.220001  23046600

In [21]:
df.shape

(1245, 5)

In [22]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1245 entries, 2021-05-28 to 2026-05-26
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1245 non-null   float64
 1   High    1245 non-null   float64
 2   Low     1245 non-null   float64
 3   Open    1245 non-null   float64
 4   Volume  1245 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.4 KB

In [23]:
# Cálculo da Média Móvel Exponencial (EMA) de 60 dias
df['EMA_60'] = df['Close'].ewm(span=60, adjust=False).mean()

In [24]:
print(df[["Close", "EMA_60"]].head(65))
print(f"Valores nulos na EMA_60: {df['EMA_60'].isna().sum()}")

Price           Close     EMA_60
2021-05-28  19.119923  19.119923
2021-05-31  19.061853  19.118019
2021-06-01  19.755884  19.138932
2021-06-02  20.414419  19.180752
2021-06-04  20.840530  19.235171
...               ...        ...
2021-08-24  20.069521  19.592672
2021-08-25  20.095465  19.609157
2021-08-26  19.609131  19.609156
2021-08-27  19.946316  19.620210
2021-08-30  19.803663  19.626225

[65 rows x 2 columns]
Valores nulos na EMA_60: 0

In [25]:
# Captando informações adicionais sobre o dataset, como valores ausentes, estatísticas descritivas e linhas com volume zerado
print("=== Valores ausentes ===")
print(df.isnull().sum())

print("\n=== Estatísticas descritivas ===")
print(df.describe())

print("\n=== Linhas com volume zerado ===")
zero_vol = df[df["Volume"] == 0]
print(f"Total: {len(zero_vol)}")
print(zero_vol)

=== Valores ausentes ===
Price
Close     0
High      0
Low       0
Open      0
Volume    0
EMA_60    0
dtype: int64

=== Estatísticas descritivas ===
Price        Close         High          Low         Open        Volume  \
count  1245.000000  1245.000000  1245.000000  1245.000000  1.245000e+03
mean     24.266988    24.520523    24.015551    24.265660  3.278910e+07
std       8.190942     8.257615     8.125305     8.193935  1.613242e+07
min      13.783373    14.020221    13.757054    13.939863  6.695412e+06
25%      17.839106    18.018837    17.643580    17.837233  2.189883e+07
50%      21.934736    22.133820    21.692997    21.920520  2.940418e+07
75%      27.895020    28.097310    27.610829    27.804487  4.028000e+07
max      48.905392    49.202568    48.142637    48.588401  1.820390e+08

Price       EMA_60
count  1245.000000
mean     23.719128
std       7.557685
min      15.168898
25%      17.599716
50%      20.100140
75%      26.834224
max      43.791737

=== Linhas com volume zerado ===
Total: 0
Empty DataFrame
Columns: [Close, High, Low, Open, Volume, EMA_60]
Index: []

In [26]:
df.head()

Price           Close       High        Low       Open    Volume     EMA_60
2021-05-28  19.119923  19.190903  18.713389  18.752107  29988923  19.119923
2021-05-31  19.061853  19.313517  18.965059  19.145740  17563652  19.118019
2021-06-01  19.755884  19.755884  19.239391  19.265215  48906171  19.138932
2021-06-02  20.414419  20.524174  19.775258  19.788170  64182184  19.180752
2021-06-04  20.840530  20.905092  20.298212  20.382142  41730769  19.235171

In [27]:
# Removendo linhas com volume zerado
df = df[df["Volume"] > 0]
print(f"Dataset após remoção de linhas com volume zerado: {df.shape}")

Dataset após remoção de linhas com volume zerado: (1245, 6)

In [28]:
#Gerando arquivo CSV do dataset processado
df.to_csv("/Users/lucaszaninidasilva/Mackenzie/SetimoSemestre/IA/PROJETO/src/database/raw/ITUB4_raw.csv", index=True)